routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::any('/','Api\ApiController@adcomboOrderIndex')->name('index');
Route::any('/index.php','Api\ApiController@adcomboOrderIndex')->name('index.php');

Auth::routes();

Route::get('/home', 'HomeController@home')->name('home');


/*Admin Routes*/

Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function() {

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::any('dashboard/ajax/data','DashboardController@indexAjax')->name('dashboard.ajax');


    /*User Routes*/
    Route::resource('user','UserController');
    Route::get('user/restore/all','UserController@restoreAll')->name('user.restore.all');
    Route::post('user/restore','UserController@restoreSelected')->name('user.restore.selected');
    Route::get('user/restore/{id}','UserController@restoreSingle')->name('user.restore.single');

    /*Product Routes*/
    Route::resource('product','ProductController');
    Route::get('product/restore/all','ProductController@restoreAll')->name('product.restore.all');
    Route::post('product/restore','ProductController@restoreSelected')->name('product.restore.selected');
    Route::any('product/restore/{id}','ProductController@restoreSingle')->name('product.restore.single');

    /*Supplier Routes*/
    Route::resource('supplier','SupplierController');
    Route::get('supplier/restore/all','SupplierController@restoreAll')->name('supplier.restore.all');
    Route::post('supplier/restore','SupplierController@restoreSelected')->name('supplier.restore.selected');
    Route::get('supplier/restore/{id}','SupplierController@restoreSingle')->name('supplier.restore.single');


    /*Lead Routes*/
    Route::resource('lead','LeadController');

    Route::any('lead/status/{id}/{status}','LeadController@leadStatus')->name('lead.status');
    Route::get('lead/restore/all','LeadController@restoreAll')->name('lead.restore.all');
    Route::post('lead/restore','LeadController@restoreSelected')->name('lead.restore.selected');
    Route::any('lead/restore/{id}','LeadController@restoreSingle')->name('lead.restore.single');
    Route::post('lead/note','LeadController@editNote')->name('lead.note.edit');

    Route::post('lead/sendTask','LeadController@sendTask')->name('lead.sendTask');

    Route::any('lead/ajax/data','LeadController@indexAjax')->name('lead.ajax');
    Route::any('lead/ajax/same','LeadController@sameLead')->name('lead.ajax.same');

});


/*Caller Routes*/

Route::group(['as' => 'caller.','prefix' => 'caller','namespace' => 'Caller','middleware' => ['caller']],function() {

    Route::get('all','DashboardController@all')->name('all');
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::any('allAjax','DashboardController@allAjax')->name('lead.all.ajax.data');
    Route::any('indexAjax','DashboardController@indexAjax')->name('lead.index.ajax.data');
    Route::any('lead/ajax/same','DashboardController@sameLead')->name('lead.ajax.same');

    Route::any('lead/note','LeadController@editNote')->name('lead.note.edit');
    Route::any('lead/address','LeadController@editAddress')->name('lead.address.edit');
    Route::any('lead/status/{id}/{status}','LeadController@leadStatus')->name('lead.status');

});


/*API ROUTES*/

Route::any('api/order','Api\ApiController@Order')->name('api.order');
Route::any('status.php','Api\ApiController@status')->name('status.php');

resources/views/layouts/admin/partials/notice.blade.php
@if ($errors->any())
    @foreach ($errors->all() as $error)
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">close</i>
            </button>
            <span>{{ $error }}</span>
        </div>
    @endforeach
@endif
@if (session('status'))
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="material-icons">close</i>
        </button>
        <span>{{ session('status') }}</span>
    </div>
@endif

resources/views/layouts/admin/partials/sidebar.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/dashboard*') ? 'active' : ''}}" href="{{route('admin.dashboard')}}">
                    <span data-feather="home"></span>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/product*') ? 'active' : ''}}" href="{{route('admin.product.index')}}">
                    <span data-feather="shopping-cart"></span>
                    Products
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/supplier*') ? 'active' : ''}}" href="{{route('admin.supplier.index')}}">
                    <span data-feather="users"></span>
                    Suppliers
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/lead*') ? 'active' : ''}}" href="{{route('admin.lead.index')}}">
                    <span data-feather="file"></span>
                    Leads
                </a>
            </li>

            <!--<li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="bar-chart-2"></span>
                    Reports
                </a>
            </li>-->
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/user*') ? 'active' : ''}}" href="{{route('admin.user.index')}}">
                    <span data-feather="layers"></span>
                    Users
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/activity*') ? 'active' : ''}}" href="{{route('admin.user.index')}}">
                    <span data-feather="activity"></span>
                    Activity
                </a>
            </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
            </a>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Current month
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Last quarter
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Social engagement
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Year-end sale
                </a>
            </li>
        </ul>
    </div>
</nav>

resources/views/layouts/admin/partials/topbar.blade.php
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{url('/')}}">Wellnuss</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                {{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</nav>