routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::any('/','Api\ApiController@adcomboOrderIndex')->name('index');
Route::any('/index.php','Api\ApiController@adcomboOrderIndex')->name('index.php');

Auth::routes();

Route::get('/home', 'HomeController@home')->name('home');


/*Admin Routes*/

Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function() {

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::any('dashboard/ajax/data','DashboardController@indexAjax')->name('dashboard.ajax');


    /*User Routes*/
    Route::resource('user','UserController');
    Route::get('user/restore/all','UserController@restoreAll')->name('user.restore.all');
    Route::post('user/restore','UserController@restoreSelected')->name('user.restore.selected');
    Route::get('user/restore/{id}','UserController@restoreSingle')->name('user.restore.single');

    /*Product Routes*/
    Route::resource('product','ProductController');
    Route::get('product/restore/all','ProductController@restoreAll')->name('product.restore.all');
    Route::post('product/restore','ProductController@restoreSelected')->name('product.restore.selected');
    Route::any('product/restore/{id}','ProductController@restoreSingle')->name('product.restore.single');

    /*Supplier Routes*/
    Route::resource('supplier','SupplierController');
    Route::get('supplier/restore/all','SupplierController@restoreAll')->name('supplier.restore.all');
    Route::post('supplier/restore','SupplierController@restoreSelected')->name('supplier.restore.selected');
    Route::get('supplier/restore/{id}','SupplierController@restoreSingle')->name('supplier.restore.single');


    /*Lead Routes*/
    Route::resource('lead','LeadController');

    Route::any('lead/status/{id}/{status}','LeadController@leadStatus')->name('lead.status');
    Route::get('lead/restore/all','LeadController@restoreAll')->name('lead.restore.all');
    Route::post('lead/restore','LeadController@restoreSelected')->name('lead.restore.selected');
    Route::any('lead/restore/{id}','LeadController@restoreSingle')->name('lead.restore.single');
    Route::post('lead/note','LeadController@editNote')->name('lead.note.edit');

    Route::post('lead/sendTask','LeadController@sendTask')->name('lead.sendTask');

    Route::any('lead/ajax/data','LeadController@indexAjax')->name('lead.ajax');
    Route::any('lead/ajax/same','LeadController@sameLead')->name('lead.ajax.same');

});


/*Caller Routes*/

Route::group(['as' => 'caller.','prefix' => 'caller','namespace' => 'Caller','middleware' => ['caller']],function() {

    Route::get('all','DashboardController@all')->name('all');
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::any('allAjax','DashboardController@allAjax')->name('lead.all.ajax.data');
    Route::any('indexAjax','DashboardController@indexAjax')->name('lead.index.ajax.data');
    Route::any('lead/ajax/same','DashboardController@sameLead')->name('lead.ajax.same');

    Route::any('lead/note','LeadController@editNote')->name('lead.note.edit');
    Route::any('lead/address','LeadController@editAddress')->name('lead.address.edit');
    Route::any('lead/status/{id}/{status}','LeadController@leadStatus')->name('lead.status');

});


/*API ROUTES*/

Route::any('api/order','Api\ApiController@Order')->name('api.order');
Route::any('status.php','Api\ApiController@status')->name('status.php');

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    public function Leads(){
        return $this->hasMany('App\Models\Lead');
    }
}

app/Http/Controllers/Admin/SupplierController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Supplier;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suppliers = Supplier::all();
        $trashes = Supplier::onlyTrashed()->get();

        return response()->view('admin.supplier.index',compact('suppliers','trashes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return response()->view('admin.supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|max:100',
            'phone' => 'max:16',
            'email' => 'email|max:150',
            'address' => 'max:200',
            'note' => 'max:500',
            'api' => 'required'
        ]);


        $supplier = new Supplier();
        $supplier->user_id = Auth::check() ? Auth::id() : 0;
        $supplier->name = $request->name;
        $supplier->api = $request->api;
        $supplier->phone = $request->phone;
        $supplier->email = $request->email;
        $supplier->address = $request->address;
        $supplier->note = $request->note;
        $supplier->status = true;
        $supplier->save();

        return redirect()->route('admin.supplier.index')
                          ->with('status','Supplier Added Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $supplier = Supplier::find($id);
        $leadData = $supplier->Leads();
        $leads    = $leadData->get();

        $leadc      =    $leadData->select('leads.id','products.name')
                                  ->join('products','products.id','=','leads.product_id')
                                  ->get()
                                  ->groupBy(function ($data){
                                      return $data->name;
                                  })

        ;

        $chart = [];
        $chart[] = ['Products','Leads'];

        foreach ($leadc as $s => $l){
            $chart[] = [$s,count($l)];
        }

        return response()->view('admin.supplier.show',compact('supplier','chart','leads'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = Supplier::find($id);

        return response()->view('admin.supplier.edit',compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|max:100',
            'phone' => 'max:16',
            'email' => 'email|max:150',
            'address' => 'max:200',
            'note' => 'max:500'
        ]);


        $supplier = Supplier::find($id);
        $supplier->user_id = Auth::check() ? Auth::id() : 0;
        $supplier->name = $request->name;
        $supplier->phone = $request->phone;
        $supplier->email = $request->email;
        $supplier->address = $request->address;
        $supplier->note = $request->note;
        $supplier->status = true;
        $supplier->save();

        return redirect()->back()
            ->with('status','Supplier Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::withTrashed()->find($id);

        if($supplier->trashed()){
            $supplier->forceDelete();
        }else{
            $supplier->delete();
        }

        return redirect()->back()
            ->with('status','User Deleted Successfully');
    }



    public function restoreSingle($id){

        Supplier::withTrashed()->find($id)
            ->restore();

        return redirect()->back()
            ->with('status','User Deleted Successfully');
    }



    public function restoreSelected($ids){

        Supplier::withTrashed()->whereIn($ids)
            ->restore();

        return redirect()->back()
            ->with('status','Selected User Successfully Restored');
    }



    public function restoreAll(){

        Supplier::withTrashed()->restore();

        return redirect()->back()
            ->with('status','User Successfully Restored.');
    }

}

resources/views/admin/supplier/create.blade.php
@extends('layouts.admin.app')

@section('title','Add Supplier')

@push('css')


@endpush


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Supplier</h1>
    </div>

    <div class="col-xs-10 col-md-6 mb-5">
        <form action="{{route('admin.supplier.store')}}" method="post">
            @csrf
            @method('POST')
            <div class="form-group">
                <label for="phone">API</label>
                <input type="text" name="api" class="form-control" id="api" value="{{uniqid().strrev(uniqid()).uniqid('a1imify',false)}}" readonly>
            </div>

            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Name">
            </div>

            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" name="phone" class="form-control" id="phone" placeholder="Phone">
            </div>

            <div class="form-group">
                <label for="name">Email</label>
                <input type="email" name="email" class="form-control" id="email" placeholder="Email">
            </div>

            <div class="form-group">
                <label for="name">Address</label>
                <textarea name="address" class="form-control" rows="1"></textarea>
            </div>

            <div class="form-group">
                <label for="email">Note</label>
                <textarea class="form-control" name="note"></textarea>
            </div>

            <!--<div class="form-group">
                <label for="phone" class="form-label form-control-file">Status</label>
                <input type="checkbox" name="status" class="form-check-inline" id="status" value="1"> <label for="status" class="form-check-label">Active</label>
            </div>-->
            <a class="btn btn-danger" href="{{route('admin.supplier.index')}}">Back</a> <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/supplier/edit.blade.php
@extends('layouts.admin.app')

@section('title','Edit Supplier')

@push('css')


@endpush


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Supplier</h1>
    </div>

    <div class="col-xs-10 col-md-6 mb-5">
        <form action="{{route('admin.supplier.update',$supplier->id)}}" method="post">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="phone">API</label>
                <input type="text" name="api" class="form-control" id="api" value="{{$supplier->api}}" disabled>
            </div>

            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{$supplier->name}}">
            </div>

            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" name="phone" class="form-control" id="phone" value="{{$supplier->phone}}">
            </div>

            <div class="form-group">
                <label for="name">Email</label>
                <input type="email" name="email" class="form-control" id="email" value="{{$supplier->email}}">
            </div>

            <div class="form-group">
                <label for="name">Address</label>
                <textarea name="address" class="form-control" rows="1">{{$supplier->address}}</textarea>
            </div>

            <div class="form-group">
                <label for="email">Note</label>
                <textarea class="form-control" name="note">{{$supplier->note}}</textarea>
            </div>

            <!--<div class="form-group">
                <label for="phone" class="form-label form-control-file">Status</label>
                <input type="checkbox" name="status" class="form-check-inline" id="status" value="1"> <label for="status" class="form-check-label">Active</label>
            </div>-->
            <a class="btn btn-danger" href="{{route('admin.supplier.index')}}">Back</a> <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/supplier/index.blade.php
@extends('layouts.admin.app')

@section('title','Suppliers')

@push('css')


@endpush


@section('content')
    <a href="{{route('admin.supplier.create')}}" class="btn btn-success mt-4 mb-4">Add</a>
    @if($suppliers->count() || $trashes->count())
        <h2>Suppliers</a></h2>
        <a href="{{route('admin.supplier.index')}}">Active Suppliers ({{$suppliers->count()}})</a>
        - <a href="{{route('admin.supplier.index',['type' => 'trash'])}}">Trash ({{$trashes->count()}})</a>
        - <a href="{{route('admin.supplier.restore.all')}}">Restore All</a>

        <div class="table-responsive">
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                <tr>
                    <th>#ID</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Note</th>
                    <th>API Info</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>

                @foreach((isset($_REQUEST['type']) && $_REQUEST['type'] == 'trash' ? $trashes : $suppliers) as $supplier)
                    <tr>
                        <td>{{$supplier->id}}</td>
                        <td>{{$supplier->name}}</td>
                        <td>{{$supplier->phone}}</td>
                        <td>{{$supplier->email}}</td>
                        <td>{{$supplier->address}}</td>
                        <td>{{$supplier->note}}</td>
                        <td class="text-center"><a href="javascript:void(0)" data-id="{{$supplier->id}}" data-key="{{$supplier->api}}" data-toggle="modal" data-target="#apiModal" id="apiInfo" class="apiInfo"><i class="fa fa-eyedropper"></i></a></td>
                        <td>
                            @if(isset($_REQUEST['type']) && $_REQUEST['type'] == 'trash')

                                <a href="{{route('admin.supplier.restore.single',$supplier->id)}}" class="restore-item" data-src="{{$supplier->id}}"><i class="fa fa-undo" aria-hidden="true"></i></a>

                            @else
                                <a href="{{route('admin.supplier.show',$supplier->id)}}"><i class="fa fa-eye"></i></a>
                                <a href="{{route('admin.supplier.edit',$supplier->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            @endif

                            <a href="javascript:void(0)" class="delete-item" data-src="{{$supplier->id}}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    @else
        <div class="text-warning text-center">No data available.</div>
    @endif


    <!-- Modal -->
    <div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="apiModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="noteModalLabel">API Info</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="modal-supplier-id" class="row border-bottom mb-2 p-2"></div>
                        <div id="modal-api-key" class="row border-bottom mb-2 p-2"></div>
                        <div class="p-5">
                            <div class="row border mb-2 p-2">
                                <b>URL :</b> <span class="ml-3">{{route('api.order')}}</span>
                            </div>
                            <div class="row border mb-2 p-2">
                                <b>Request Type :</b>  <span class="ml-3">GET / POST</span>
                            </div>
                            <div class="row border mb-2 p-2">
                               <b> Parameters : </b> <span class="ml-3">product_id*, supplier_id*, api_key*, name*, phone*, email, address, order_id, publisher_id
                            </span>
                            </div>

                            <div class="row border mb-2 p-2">
                                <b>Note :</b>  <span class="ml-3">* parameters are must required.</span>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
            </div>
        </div>
    </div>

@endsection


@push('script')
    <script>
        $(document).ready(function() {
            $('#example').DataTable({
                 destroy: true,
                 bDestroy: true,
                "ordering": false,
                "info":     false,
                "lengthChange": false
            });


            $(".delete-item").click(function () {

                let deleteForm = document.createElement('form'),
                    currentURL = `{{route('admin.supplier.destroy','deleteid')}}`,
                    deleteURL = currentURL.replace('deleteid',this.dataset.src),
                    csrfInput = document.createElement('input'),
                    methodInput = document.createElement('input')
                deleteForm.style.display = 'none';
                deleteForm.method = 'POST'
                deleteForm.action = deleteURL
                csrfInput.name = `_token`
                csrfInput.value = `{{csrf_token()}}`
                methodInput.name = `_method`
                methodInput.value = `DELETE`
                deleteForm.appendChild(csrfInput)
                deleteForm.appendChild(methodInput)
                document.body.appendChild(deleteForm)
                deleteForm.submit()
            })

            $(".apiInfo").click(function () {
                $("#modal-supplier-id").html(`<b>Supplier ID :</b><span class="ml-3">`+this.dataset.id+`</span>`)
                $("#modal-api-key").html(`<b>API Key :<b><span class="ml-3">`+this.dataset.key+`</span>`)
            })

        } );
    </script>
@endpush

resources/views/admin/supplier/show.blade.php
@extends('layouts.admin.app')

@section('title','Show')

@push('css')

<script src="{{asset('js/admin/piechart.js')}}"></script>
@endpush


@section('content')
    <div class="text-center">
        <span class="btn btn-status-confirm"></span> Confirm
        <span class="btn btn-status-cancel"></span> Cancel
        <span class="btn btn-status-hold"></span> Hold
        <span class="btn btn-status-trash"></span> Trash
    </div>
    <div id="piechart" style="height: 500px;"></div>

    <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>#ID</th>
                <th>Product ID</th>
                <th>Order ID</th>
                <th>DateTime</th>
                <th>Customer</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Address</th>
                <th>Status Admin</th>
                <th>Status Caller</th>
                <th>Note</th>
            </tr>
            </thead>
            <tbody>
            @foreach($leads as $lead)
            <tr>
                <td>{{$lead->supplier_serial}}</td>
                <td>{{$lead->product_id}}</td>
                <td>{{$lead->order_id}}</td>
                <td>{{$lead->created_at}}</td>
                <td>{{$lead->name}}</td>
                <td>{{$lead->phone}}</td>
                <td>{{$lead->email}}</td>
                <td>{{$lead->address}}</td>
                <td><span class="{{$lead->AdminStatus->class??''}}" title="{{$lead->AdminStatus->title??''}}"></span></td>
                <td><span class="{{$lead->CallerStatus->class??''}}" title="{{$lead->CallerStatus->title??''}}"></span></td>
                <td>{{$lead->note}}</td>
            </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection


@push('script')
    <script type="text/javascript">
        $(document).ready(function() {

            google.charts.load("current", {packages: ["corechart"]});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                var data = google.visualization.arrayToDataTable(<?php echo json_encode($chart); ?>);

                var options = {
                    title: `{{$supplier->name}} #{{$supplier->id}}`,
                    is3D: true,
                };

                var chart = new google.visualization.PieChart(document.getElementById('piechart'));
                chart.draw(data, options);
            }

            $('#example').DataTable({
                destroy: true,
                bDestroy: true,
                "ordering": false,
                "info": false,
                "lengthChange": false
            });
        })
    </script>

@endpush