routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::any('/','Api\ApiController@adcomboOrderIndex')->name('index');
Route::any('/index.php','Api\ApiController@adcomboOrderIndex')->name('index.php');

Auth::routes();

Route::get('/home', 'HomeController@home')->name('home');


/*Admin Routes*/

Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function() {

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::any('dashboard/ajax/data','DashboardController@indexAjax')->name('dashboard.ajax');


    /*User Routes*/
    Route::resource('user','UserController');
    Route::get('user/restore/all','UserController@restoreAll')->name('user.restore.all');
    Route::post('user/restore','UserController@restoreSelected')->name('user.restore.selected');
    Route::get('user/restore/{id}','UserController@restoreSingle')->name('user.restore.single');

    /*Product Routes*/
    Route::resource('product','ProductController');
    Route::get('product/restore/all','ProductController@restoreAll')->name('product.restore.all');
    Route::post('product/restore','ProductController@restoreSelected')->name('product.restore.selected');
    Route::any('product/restore/{id}','ProductController@restoreSingle')->name('product.restore.single');

    /*Supplier Routes*/
    Route::resource('supplier','SupplierController');
    Route::get('supplier/restore/all','SupplierController@restoreAll')->name('supplier.restore.all');
    Route::post('supplier/restore','SupplierController@restoreSelected')->name('supplier.restore.selected');
    Route::get('supplier/restore/{id}','SupplierController@restoreSingle')->name('supplier.restore.single');


    /*Lead Routes*/
    Route::resource('lead','LeadController');

    Route::any('lead/status/{id}/{status}','LeadController@leadStatus')->name('lead.status');
    Route::get('lead/restore/all','LeadController@restoreAll')->name('lead.restore.all');
    Route::post('lead/restore','LeadController@restoreSelected')->name('lead.restore.selected');
    Route::any('lead/restore/{id}','LeadController@restoreSingle')->name('lead.restore.single');
    Route::post('lead/note','LeadController@editNote')->name('lead.note.edit');

    Route::post('lead/sendTask','LeadController@sendTask')->name('lead.sendTask');

    Route::any('lead/ajax/data','LeadController@indexAjax')->name('lead.ajax');
    Route::any('lead/ajax/same','LeadController@sameLead')->name('lead.ajax.same');

});


/*Caller Routes*/

Route::group(['as' => 'caller.','prefix' => 'caller','namespace' => 'Caller','middleware' => ['caller']],function() {

    Route::get('all','DashboardController@all')->name('all');
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::any('allAjax','DashboardController@allAjax')->name('lead.all.ajax.data');
    Route::any('indexAjax','DashboardController@indexAjax')->name('lead.index.ajax.data');
    Route::any('lead/ajax/same','DashboardController@sameLead')->name('lead.ajax.same');

    Route::any('lead/note','LeadController@editNote')->name('lead.note.edit');
    Route::any('lead/address','LeadController@editAddress')->name('lead.address.edit');
    Route::any('lead/status/{id}/{status}','LeadController@leadStatus')->name('lead.status');

});


/*API ROUTES*/

Route::any('api/order','Api\ApiController@Order')->name('api.order');
Route::any('status.php','Api\ApiController@status')->name('status.php');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    public $incrementing = false;

    public function Leads(){
        return $this->hasMany('App\Models\Lead');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ProductController extends Controller
{
    private $directory = 'uploads/products/';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $trashes = Product::onlyTrashed()->get();

      return response()->view('admin.product.index',compact('products','trashes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return response()->view('admin.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request,[
          'name' => 'required|max:100',
          'image' => 'mimes:jpg,png,bmp,gif,jpeg',
          'id'    => 'required|unique:products,id'
      ]);

      $image = $request->file('image');
      $image_name = 'default.png';


      if(is_file($image)){
          $image_name = str_slug($request->name).uniqid().'.'.$image->getClientOriginalExtension();

          if (!Storage::disk('public')->exists($this->directory)) {
              Storage::disk('public')->makeDirectory($this->directory);
          }

          $productImage = Image::make($image)->resize(512,512)->save('tmp/tmp.'.$image->getClientOriginalExtension());
          Storage::disk('public')->put($this->directory.$image_name,$productImage);
      }

      $product = new Product();
      $product->user_id = Auth::check() ? Auth::id() : 0;
      $product->id = $request->id;
      $product->name = $request->name;
      $product->note = $request->note??'';
      $product->status = true;
      $product->image = $this->directory.$image_name;
      $product->save();

      return redirect()->route('admin.product.index')
                        ->with('status','Product Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        $leadData   =     $product->Leads();
        $leads      =     $leadData->get();
        $leadc      =     $leadData->select('leads.id','suppliers.name')
                                  ->join('suppliers','suppliers.id','=','leads.supplier_id')
                                  ->get()
                                  ->groupBy(function ($data){
                                      return $data->name;
                                  })

        ;

        $chart = [];
        $chart[] = ['Suppliers','Leads'];

        foreach ($leadc as $s => $l){
            $chart[] = [$s,count($l)];
        }


        return response()->view('admin.product.show',compact('product','chart','leads'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        return response()->view('admin.product.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|max:100',
            'image' => 'mimes:jpg,png,bmp,gif,jpeg',
            'id'    => 'required|unique:products,id,'.$id
        ]);

        $product = Product::find($id);
        $image = $request->file('image');
        $image_name = $product->image;


        if(is_file($image)){
            $image_name = str_slug($request->name).uniqid().'.'.$image->getClientOriginalExtension();

            if (!Storage::disk('public')->exists($this->directory)) {
                Storage::disk('public')->makeDirectory($this->directory);
            }

            if(Storage::disk('public')->exists($product->image)){
                Storage::disk('public')->delete($product->image);
            }

            $productImage = Image::make($image)->resize(512,512)->save('tmp/tmp.'.$image->getClientOriginalExtension());
            Storage::disk('public')->put($this->directory.$image_name,$productImage);
        }

        $product->user_id = Auth::check() ? Auth::id() : 0;
        $product->id = $request->id;
        $product->name = $request->name;
        $product->note = $request->note??'';
        $product->status = true;
        $product->image = $this->directory.$image_name;
        $product->save();

        return redirect()->route('admin.product.index')
            ->with('status','Product Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::withTrashed()->find($id);

        if($product->trashed()){

            if(Storage::disk('public')->exists($product->image)){
                Storage::disk('public')->delete($product->image);
            }

            $product->forceDelete();

        }else{
            $product->delete();
        }

        return redirect()->back()
            ->with('status','User Deleted Successfully');
    }



    public function restoreSingle($id){

        Product::withTrashed()->find($id)
            ->restore();

        return redirect()->back()
            ->with('status','User Deleted Successfully');
    }



    public function restoreSelected($ids){

        Product::withTrashed()->whereIn($ids)
            ->restore();

        return redirect()->back()
            ->with('status','Selected User Successfully Restored');
    }



    public function restoreAll(){

        Product::withTrashed()->restore();

        return redirect()->back()
            ->with('status','User Successfully Restored.');
    }


}

resources/views/admin/product/create.blade.php
@extends('layouts.admin.app')

@section('title','Add Product')

@push('css')


@endpush


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Product</h1>
    </div>

    <div class="col-xs-10 col-md-6 mb-5">
        <form action="{{route('admin.product.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('POST')
            <div class="form-group">
                <label for="id">ID</label>
                <input type="text" name="id" class="form-control" id="id" placeholder="ID">
            </div>

            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="email">Note</label>
                <textarea class="form-control" name="note"></textarea>
            </div>

            <div class="form-group">
                <label for="phone">Image</label>
                <input type="file" name="image" class="form-control-file" id="image">
            </div>

            <!--<div class="form-group">
                <label for="phone" class="form-label form-control-file">Status</label>
                <input type="checkbox" name="status" class="form-check-inline" id="status" value="1"> <label for="status" class="form-check-label">Active</label>
            </div>-->
            <a class="btn btn-danger" href="{{route('admin.user.index')}}">Back</a> <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/product/edit.blade.php
@extends('layouts.admin.app')

@section('title','Edit Product')

@push('css')


@endpush


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Product</h1>
    </div>

    <div class="col-xs-10 col-md-6 mb-5">
        <form action="{{route('admin.product.update',$product->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="id">ID</label>
                <input type="text" name="id" class="form-control" id="id" value="{{$product->id}}">
            </div>

            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{$product->name}}">
            </div>
            <div class="form-group">
                <label for="email">Note</label>
                <textarea class="form-control" name="note">{{$product->note}}</textarea>
            </div>

            <div class="form-group">
                <label for="phone">Image</label>
                <img src="{{asset($product->image)}}">
                <input type="file" name="image" class="form-control-file" id="image">
            </div>

            <!--<div class="form-group">
                <label for="phone" class="form-label form-control-file">Status</label>
                <input type="checkbox" name="status" class="form-check-inline" id="status" value="1"> <label for="status" class="form-check-label">Active</label>
            </div>-->
            <a class="btn btn-danger" href="{{route('admin.user.index')}}">Back</a> <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/product/index.blade.php
@extends('layouts.admin.app')

@section('title','Products')

@push('css')


@endpush


@section('content')
    <a href="{{route('admin.product.create')}}" class="btn btn-success mt-4 mb-4">Add</a>
    @if($products->count() || $trashes->count())
        <h2>Products</a></h2>
        <a href="{{route('admin.product.index')}}">Active Products ({{$products->count()}})</a>
        - <a href="{{route('admin.product.index',['type' => 'trash'])}}">Trash ({{$trashes->count()}})</a>
        - <a href="{{route('admin.product.restore.all')}}">Restore All</a>

        <div class="table-responsive">
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                <tr>
                    <th>#ID</th>
                    <th>Name</th>
                    <th>Note</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>

                @foreach((isset($_REQUEST['type']) && $_REQUEST['type'] == 'trash' ? $trashes : $products) as $product)
                    <tr>
                        <td>{{$product->id}}</td>
                        <td>{{$product->name}}</td>
                        <td>{{$product->note}}</td>
                        <td><img src="{{asset($product->image)}}"></td>
                        <td>
                            @if(isset($_REQUEST['type']) && $_REQUEST['type'] == 'trash')
                                <a href="{{route('admin.product.restore.single',$product->id)}}" class="restore-item" data-src="{{$product->id}}"><i class="fa fa-undo" aria-hidden="true"></i></a>

                            @else
                                <a href="{{route('admin.product.show',$product->id)}}"><i class="fa fa-eye"></i></a>
                                <a href="{{route('admin.product.edit',$product->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            @endif

                            <a href="javascript:void(0)" class="delete-item" data-src="{{$product->id}}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    @else
        <div class="text-warning text-center">No data available.</div>
    @endif
@endsection


@push('script')
    <script>
        $(document).ready(function() {
            $('#example').DataTable({
                destroy: true,
                bDestroy: true,
                "ordering": false,
                "info":     false,
                "lengthChange": false
            });


            $(".delete-item").click(function () {

                let deleteForm = document.createElement('form'),
                    currentURL = `{{route('admin.product.destroy','deleteid')}}`,
                    deleteURL = currentURL.replace('deleteid',this.dataset.src),
                    csrfInput = document.createElement('input'),
                    methodInput = document.createElement('input')
                deleteForm.style.display = 'none';
                deleteForm.method = 'POST'
                deleteForm.action = deleteURL
                csrfInput.name = `_token`
                csrfInput.value = `{{csrf_token()}}`
                methodInput.name = `_method`
                methodInput.value = `DELETE`
                deleteForm.appendChild(csrfInput)
                deleteForm.appendChild(methodInput)
                document.body.appendChild(deleteForm)
                deleteForm.submit()
            })


        } );
    </script>
@endpush

resources/views/admin/product/show.blade.php
@extends('layouts.admin.app')

@section('title','Show')

@push('css')

<script src="{{asset('js/admin/piechart.js')}}"></script>
@endpush


@section('content')
    <div class="text-center">
        <span class="btn btn-status-confirm"></span> Confirm
        <span class="btn btn-status-cancel"></span> Cancel
        <span class="btn btn-status-hold"></span> Hold
        <span class="btn btn-status-trash"></span> Trash
    </div>
    <div id="piechart" style="height: 500px;"></div>


    <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>#ID</th>
                <th>Order ID</th>
                <th>DateTime</th>
                <th>Supplier</th>
                <th>Customer</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Address</th>
                <th>Status Admin</th>
                <th>Status Caller</th>
                <th>Note</th>
            </tr>
            </thead>
            <tbody>
            @foreach($leads as $lead)
                <tr>
                    <td>{{$lead->supplier_serial}}</td>
                    <td>{{$lead->order_id}}</td>
                    <td>{{$lead->created_at}}</td>
                    <td>{{$lead->Supplier->name??''}}</td>
                    <td>{{$lead->name}}</td>
                    <td>{{$lead->phone}}</td>
                    <td>{{$lead->email}}</td>
                    <td>{{$lead->address}}</td>
                    <td><span class="{{$lead->AdminStatus->class??''}}" title="{{$lead->AdminStatus->title??''}}"></span></td>
                    <td><span class="{{$lead->CallerStatus->class??''}}" title="{{$lead->CallerStatus->title??''}}"></span></td>
                    <td>{{$lead->note}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection


@push('script')
    <script type="text/javascript">
        $(document).ready(function() {

            google.charts.load("current", {packages: ["corechart"]});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                var data = google.visualization.arrayToDataTable(<?php echo json_encode($chart); ?>);

                var options = {
                    title: `{{$product->name}} #{{$product->id}}`,
                    is3D: true,
                };

                var chart = new google.visualization.PieChart(document.getElementById('piechart'));
                chart.draw(data, options);
            }

            $('#example').DataTable({
                destroy: true,
                bDestroy: true,
                "ordering": false,
                "info": false,
                "lengthChange": false
            });
        })
    </script>
@endpush