routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::any('/','Api\ApiController@adcomboOrderIndex')->name('index');
Route::any('/index.php','Api\ApiController@adcomboOrderIndex')->name('index.php');

Auth::routes();

Route::get('/home', 'HomeController@home')->name('home');


/*Admin Routes*/

Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function() {

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::any('dashboard/ajax/data','DashboardController@indexAjax')->name('dashboard.ajax');


    /*User Routes*/
    Route::resource('user','UserController');
    Route::get('user/restore/all','UserController@restoreAll')->name('user.restore.all');
    Route::post('user/restore','UserController@restoreSelected')->name('user.restore.selected');
    Route::get('user/restore/{id}','UserController@restoreSingle')->name('user.restore.single');

    /*Product Routes*/
    Route::resource('product','ProductController');
    Route::get('product/restore/all','ProductController@restoreAll')->name('product.restore.all');
    Route::post('product/restore','ProductController@restoreSelected')->name('product.restore.selected');
    Route::any('product/restore/{id}','ProductController@restoreSingle')->name('product.restore.single');

    /*Supplier Routes*/
    Route::resource('supplier','SupplierController');
    Route::get('supplier/restore/all','SupplierController@restoreAll')->name('supplier.restore.all');
    Route::post('supplier/restore','SupplierController@restoreSelected')->name('supplier.restore.selected');
    Route::get('supplier/restore/{id}','SupplierController@restoreSingle')->name('supplier.restore.single');


    /*Lead Routes*/
    Route::resource('lead','LeadController');

    Route::any('lead/status/{id}/{status}','LeadController@leadStatus')->name('lead.status');
    Route::get('lead/restore/all','LeadController@restoreAll')->name('lead.restore.all');
    Route::post('lead/restore','LeadController@restoreSelected')->name('lead.restore.selected');
    Route::any('lead/restore/{id}','LeadController@restoreSingle')->name('lead.restore.single');
    Route::post('lead/note','LeadController@editNote')->name('lead.note.edit');

    Route::post('lead/sendTask','LeadController@sendTask')->name('lead.sendTask');

    Route::any('lead/ajax/data','LeadController@indexAjax')->name('lead.ajax');
    Route::any('lead/ajax/same','LeadController@sameLead')->name('lead.ajax.same');

});


/*Caller Routes*/

Route::group(['as' => 'caller.','prefix' => 'caller','namespace' => 'Caller','middleware' => ['caller']],function() {

    Route::get('all','DashboardController@all')->name('all');
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::any('allAjax','DashboardController@allAjax')->name('lead.all.ajax.data');
    Route::any('indexAjax','DashboardController@indexAjax')->name('lead.index.ajax.data');
    Route::any('lead/ajax/same','DashboardController@sameLead')->name('lead.ajax.same');

    Route::any('lead/note','LeadController@editNote')->name('lead.note.edit');
    Route::any('lead/address','LeadController@editAddress')->name('lead.address.edit');
    Route::any('lead/status/{id}/{status}','LeadController@leadStatus')->name('lead.status');

});


/*API ROUTES*/

Route::any('api/order','Api\ApiController@Order')->name('api.order');
Route::any('status.php','Api\ApiController@status')->name('status.php');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function Role(){
        return $this->belongsTo('App\Models\Role');
    }

    public function Userextra(){
        return $this->belongsTo('App\Models\Userextra');
    }

    public function callerTask(){
        return $this->hasMany('App\Models\Lead','caller_id','id')->orWhereNotNull('update_caller');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Role;
use App\Models\Userextra;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::all();
        $trashes = User::onlyTrashed()->get();

       return response()->view('admin.user.index',compact('users','trashes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();

        return response()->view('admin.user.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'     => 'required|min:5|max:15',
            'email'    => 'required',
            'phone'    => 'required',
            'role'     => 'required',
            'password' => 'required|string|min:6|confirmed'
        ]);


        $phone = new Userextra();
        $phone->phone = $request->phone;
        $phone->save();


        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);

        $user->Userextra()->associate($phone);
        $user->Role()->associate($request->role);

        $user->save();
        return redirect()->route('admin.user.index')->with('status','User Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::all();

        return response()->view('admin.user.edit',compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'     => 'required|min:5|max:15',
            'email'    => 'required',
            'phone'    => 'required',
            'role'     => 'required'
        ]);


        if($request->password){
            $this->validate($request,[
                'password' => 'required|string|min:6|confirmed'
            ]);
        }

        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;

        if($request->password){
            $user->password = Hash::make($request->password);
        }


        $user->Role()->associate($request->role);

        $phone = Userextra::find($user->userextra_id);
        $phone->phone = $request->phone;
        $phone->save();

        $user->save();
        return redirect()->back()->with('status','User Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::withTrashed()->find($id);

        if($user->trashed()){
            $user->forceDelete();
        }else{
            $user->delete();
        }

        return redirect()->back()
                          ->with('status','User Deleted Successfully');
    }



    public function restoreSingle($id){

        User::withTrashed()->find($id)
                           ->restore();

        return redirect()->back()
                          ->with('status','User Deleted Successfully');
    }



    public function restoreSelected($ids){

        User::withTrashed()->whereIn($ids)
                           ->restore();

        return redirect()->back()
                          ->with('status','Selected User Successfully Restored');
    }



    public function restoreAll(){

        User::withTrashed()->restore();

        return redirect()->back()
                          ->with('status','User Successfully Restored.');
    }


}

resources/views/admin/user/create.blade.php
@extends('layouts.admin.app')

@section('title','Create User')

@push('css')


@endpush


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add User</h1>
    </div>

    <div class="col-xs-10 col-md-6 mb-5">
    <form action="{{route('admin.user.store')}}" method="post">
        @csrf
        @method('POST')
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" class="form-control" id="email" placeholder="Email">
        </div>

        <div class="form-group">
            <label for="phone">Phone</label>
            <input type="text" name="phone" class="form-control" id="phone" placeholder="Phone">
        </div>

        <div class="form-group">
            <label for="role">Role</label>
            <select name="role" class="form-control">
                @foreach($roles as $role)
                    <option value="{{$role->id}}">{{$role->title}}</option>
                    @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" id="password">
        </div>

        <div class="form-group">
            <label for="password">Confirm Password</label>
            <input type="password" name="password_confirmation" class="form-control" id="password">
        </div>


        <a class="btn btn-danger" href="{{route('admin.user.index')}}">Back</a> <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/user/edit.blade.php
@extends('layouts.admin.app')

@section('title','Edit User')

@push('css')


@endpush


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mb-3 pt-3 pb-2 border-bottom">
        <h1 class="h2">Create User</h1>
    </div>

    <div class="col-xs-10 col-md-6 mb-5">
        <form action="{{route('admin.user.update',$user->id)}}" method="post">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{$user->name}}">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" class="form-control" id="email" value="{{$user->email}}">
            </div>

            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" name="phone" class="form-control" id="phone" value="{{$user->Userextra->phone}}">
            </div>

            <div class="form-group">
                <label for="role">Role</label>
                <select name="role" class="form-control">
                    @foreach($roles as $role)
                        <option value="{{$role->id}}" {{$user->role_id == $role->id ? 'selected' : ''}}>{{$role->title}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>

            <div class="form-group">
                <label for="password">Confirm Password</label>
                <input type="password" name="password_confirmation" class="form-control" id="password">
            </div>


            <a class="btn btn-danger" href="{{route('admin.user.index')}}">Back</a> <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection


@push('script')

@endpush

resources/views/admin/user/index.blade.php
@extends('layouts.admin.app')

@section('title','User')

@push('css')


@endpush


@section('content')
    <a href="{{route('admin.user.create')}}" class="btn btn-success mt-4 mb-4">Add</a>
    @if($users->count() || $trashes->count())
    <h2>All Users</a></h2>
    <a href="{{route('admin.user.index')}}">Active Users ({{$users->count()}})</a>
    - <a href="{{route('admin.user.index',['type' => 'trash'])}}">Trash ({{$trashes->count()}})</a>
    - <a href="{{route('admin.user.restore.all')}}">Restore All</a>

    <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>#ID</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Role</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>

        @foreach((isset($_REQUEST['type']) && $_REQUEST['type'] == 'trash' ? $trashes : $users) as $user)
            <tr>
                <td>{{$user->id}}</td>
                <td>{{$user->name}}</td>
                <td>{{$user->Userextra->phone}}</td>
                <td>{{$user->email}}</td>
                <td>{{$user->Role->title}}</td>
                <td>
                    @if(isset($_REQUEST['type']) && $_REQUEST['type'] == 'trash')

                        <a href="{{route('admin.user.restore.single',$user->id)}}" class="restore-item" data-src="{{$user->id}}"><i class="fa fa-undo" aria-hidden="true"></i></a>

                    @else

                    <a href="{{route('admin.user.edit',$user->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    @endif

                    <a href="javascript:void(0)" class="delete-item" data-src="{{$user->id}}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        @endforeach
            </tbody>
        </table>
    </div>
            @else
            <div class="text-warning text-center">No data available.</div>
        @endif
@endsection


@push('script')
<script>
    $(document).ready(function() {
        $('#example').DataTable({
            destroy: true,
            bDestroy: true,
            "ordering": false,
            "info":     false,
            "lengthChange": false
        });


        $(".delete-item").click(function () {

            let deleteForm = document.createElement('form'),
                currentURL = `{{route('admin.user.destroy','deleteid')}}`,
                deleteURL = currentURL.replace('deleteid',this.dataset.src),
                csrfInput = document.createElement('input'),
                methodInput = document.createElement('input')
            deleteForm.style.display = 'none';
            deleteForm.method = 'POST'
            deleteForm.action = deleteURL
            csrfInput.name = `_token`
            csrfInput.value = `{{csrf_token()}}`
            methodInput.name = `_method`
            methodInput.value = `DELETE`
            deleteForm.appendChild(csrfInput)
            deleteForm.appendChild(methodInput)
            document.body.appendChild(deleteForm)
            deleteForm.submit()
        })


    } );
</script>
@endpush